flaskblog/apps/user/models.py
from datetime import datetime

from exts import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(15), nullable=False)
    password = db.Column(db.String(100), nullable=False)
    phone = db.Column(db.String(11), unique=True, nullable=False)
    email = db.Column(db.String(30))
    icon = db.Column(db.String(100))
    isdelete = db.Column(db.Boolean, default=False)
    rdatetime = db.Column(db.DateTime, default=datetime.now)
    # 增加一个字段
    articles = db.relationship('Article', backref='user')

    def __str__(self):
        return self.username

flaskblog/apps/article/views.py
from flask import Blueprint, request, g, redirect, url_for

from apps.article.models import Article
from exts import db

article_bp1 = Blueprint('article', __name__, url_prefix='/article')


@article_bp1.route('/publish', methods=['POST', 'GET'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        type_id = request.form.get('type')
        content = request.form.get('content')
        # 添加文章
        article = Article()
        article.title = title
        article.type_id = type_id
        article.content = content
        article.user_id = g.user.id
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('user.index'))

flaskblog/apps/user/views.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename

from apps.article.models import Article_type, Article
from apps.user.models import User
from apps.user.smssend import SmsSendAPIDemo
from exts import db
from settings import Config

user_bp1 = Blueprint('user', __name__, url_prefix='/user')

required_login_list = ['/user/center', '/user/change', '/article/publish']


@user_bp1.before_app_first_request
def first_request():
    print('before_app_first_request')


# ****重点*****
@user_bp1.before_app_request
def before_request1():
    print('before_request1before_request1', request.path)
    if request.path in required_login_list:
        id = session.get('uid')
        if not id:
            return render_template('user/login.html')
        else:
            user = User.query.get(id)
            # g对象，本次请求的对象
            g.user = user


@user_bp1.after_app_request
def after_request_test(response):
    response.set_cookie('a', 'bbbb', max_age=19)
    print('after_request_test')
    return response


@user_bp1.teardown_app_request
def teardown_request_test(response):
    print('teardown_request_test')
    return response

# 自定义过滤器

@user_bp1.app_template_filter('cdecode')
def content_decode(content):
    content=content.decode('utf-8')
    return content


# 首页
@user_bp1.route('/')
def index():
    # 1。cookie获取方式
    # uid = request.cookies.get('uid', None)
    # 2。session的获取,session底层默认获取
    # 2。session的方式：
    uid = session.get('uid')
    # 获取文章列表
    articles = Article.query.order_by(Article.pdatetime).all()
    # 获取分类列表
    types = Article_type.query.all()
    # 判断用户是否登录
    if uid:
        user = User.query.get(uid)
        return render_template('user/index.html', user=user, articles=articles, types=types)
    else:
        return render_template('user/index.html', articles=articles, types=types)


# 用户注册
@user_bp1.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        phone = request.form.get('phone')
        email = request.form.get('email')
        if password == repassword:
            # 注册用户
            user = User()
            user.username = username
            # 使用自带的函数实现加密：generate_password_hash
            user.password = generate_password_hash(password)
            # print(password)
            user.phone = phone
            user.email = email
            # 添加并提交
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.index'))
    return render_template('user/register.html')


# 手机号码验证
@user_bp1.route('/checkphone', methods=['GET', 'POST'])
def check_phone():
    phone = request.args.get('phone')
    user = User.query.filter(User.phone == phone).all()
    print(user)
    # code: 400 不能用    200 可以用
    if len(user) > 0:
        return jsonify(code=400, msg='此号码已被注册')
    else:
        return jsonify(code=200, msg='此号码可用')


# 用户登录
@user_bp1.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        f = request.args.get('f')
        if f == '1':  # 用户名或者密码
            username = request.form.get('username')
            password = request.form.get('password')
            users = User.query.filter(User.username == username).all()
            for user in users:
                # 如果flag=True表示匹配，否则密码不匹配
                flag = check_password_hash(user.password, password)
                if flag:
                    # 1。cookie实现机制
                    # response = redirect(url_for('user.index'))
                    # response.set_cookie('uid', str(user.id), max_age=1800)
                    # return response
                    # 2。session机制,session当成字典使用
                    session['uid'] = user.id
                    return redirect(url_for('user.index'))
            else:
                return render_template('user/login.html', msg='用户名或者密码有误')
        elif f == '2':  # 手机号码与验证码
            print('----->22222')
            phone = request.form.get('phone')
            code = request.form.get('code')
            # 先验证验证码
            valid_code = session.get(phone)
            print('valid_code:' + str(valid_code))
            if code == valid_code:
                # 查询数据库
                user = User.query.filter(User.phone == phone).first()
                print(user)
                if user:
                    # 登录成功
                    session['uid'] = user.id
                    return redirect(url_for('user.index'))
                else:
                    return render_template('user/login.html', msg='此号码未注册')
            else:
                return render_template('user/login.html', msg='验证码有误！')

    return render_template('user/login.html')


# 发送短信息
@user_bp1.route('/sendMsg')
def send_message():
    phone = request.args.get('phone')
    # 补充验证手机号码是否注册，去数据库查询

    SECRET_ID = "dcc535cbfaefa2a24c1e6610035b6586"  # 产品密钥ID，产品标识
    SECRET_KEY = "d28f0ec3bf468baa7a16c16c9474889e"  # 产品私有密钥，服务端生成签名信息使用，请严格保管，避免泄露
    BUSINESS_ID = "748c53c3a363412fa963ed3c1b795c65"  # 业务ID，易盾根据产品业务特点分配
    api = SmsSendAPIDemo(SECRET_ID, SECRET_KEY, BUSINESS_ID)
    params = {
        "mobile": phone,
        "templateId": "11732",
        "paramType": "json",
        "params": "json格式字符串"
    }
    ret = api.send(params)
    print(ret)
    # session[phone] = '189075'
    # return jsonify(code=200, msg='短信发送成功！')

    if ret is not None:
        if ret["code"] == 200:
            taskId = ret["result"]["taskId"]
            print("taskId = %s" % taskId)
            session[phone] = '189075'
            return jsonify(code=200, msg='短信发送成功！')
        else:
            print("ERROR: ret.code=%s,msg=%s" % (ret['code'], ret['msg']))
            return jsonify(code=400, msg='短信发送失败！')


# 用户退出
@user_bp1.route('/logout')
def logout():
    # 1。 cookie的方式
    # response = redirect(url_for('user.index'))
    # 通过response对象的delete_cookie(key),key就是要删除的cookie的key
    # response.delete_cookie('uid')
    # 2。session的方式
    # del session['uid']
    session.clear()
    return redirect(url_for('user.index'))


# 用户中心
@user_bp1.route('/center')
def user_center():
    types = Article_type.query.all()
    return render_template('user/center.html', user=g.user, types=types)


# 图片的扩展名
ALLOWED_EXTENSIONS = ['jpg', 'png', 'gif', 'bmp']


# 用户信息修改
@user_bp1.route('/change', methods=['GET', 'POST'])
def user_change():
    if request.method == 'POST':
        username = request.form.get('username')
        phone = request.form.get('phone')
        email = request.form.get('email')
        # 只要有文件（图片），获取方式必须使用request.files.get(name)
        icon = request.files.get('icon')
        # print('======>', icon)  # FileStorage
        # 属性： filename 用户获取文件的名字
        # 方法:  save(保存路径)
        icon_name = icon.filename  # 1440w.jpg
        suffix = icon_name.rsplit('.')[-1]
        if suffix in ALLOWED_EXTENSIONS:
            icon_name = secure_filename(icon_name)  # 保证文件名是符合python的命名规则
            file_path = os.path.join(Config.UPLOAD_ICON_DIR, icon_name)
            icon.save(file_path)
            # 保存成功
            user = g.user
            user.username = username
            user.phone = phone
            user.email = email
            path = 'upload/icon'
            user.icon = os.path.join(path, icon_name)
            db.session.commit()
            return redirect(url_for('user.user_center'))
        else:
            return render_template('user/center.html', user=g.user, msg='必须是扩展名是：jpg,png,gif,bmp格式')

        # 查询一下手机号码
        # users = User.query.all()
        # for user in users:
        #     if user.phone == phone:
        #         # 说明数据库中已经有人注册此号码
        #         return render_template('user/center.html', user=g.user,msg='此号码已被注册')
        #

    return render_template('user/center.html', user=g.user)


# 发表文章
@user_bp1.route('/article', methods=['GET', 'POST'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        type = request.form.get('type')
        content = request.form.get('content')
        print(title, type, content)

        return render_template('article/test.html', content=content)
    return '发表失败！'

flaskblog/templates/user/center.html
{% extends 'base.html' %}
{% block title %}
    用户中心
{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/center.css') }}">
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="left">
            <p>用户信息修改</p>
            <p>发表文章</p>
            <p>管理相册</p>
            <p>管理留言</p>
            <p>关于我设置</p>
        </div>
        <div id="right">
            <div class="right1">
                <h2> 用户信息修改</h2>
                <form action="{{ url_for('user.user_change') }}" method="post" enctype="multipart/form-data">
                    <p><input type="text" class="form-control" id="InputUsername" name="username"
                              value="{{ g.user.username }}">
                    </p>
                    <p><input type="text" class="form-control" id="InputPhone" name="phone"
                              value="{{ g.user.phone }}"><span></span>
                    </p>
                    <p><input type="email" class="form-control" id="InputEmail1" name="email"
                              value="{{ g.user.email }}">
                    </p>
                    <p><input type="file" id="exampleInputFile" name="icon"></p>
                    <p>
                        <img src="{% if g.user.icon %} {{ url_for('static',filename=user.icon) }} {% else %}{{ url_for('static',filename='images/touxiang.jpg') }}{% endif %}"
                             alt="" width="90"
                             height="100">
                    </p>
                    <p>
                        <button type="submit" class="btn btn-primary">用户信息修改</button>
                    </p>

                </form>
            </div>
            <div class="right1" style="padding-top: 20px">
                <form action="{{ url_for('article.publish_article') }}" method="post">
                    <p><input type="text" class="form-control" id="InputTitle" name="title"
                              placeholder="请输入文章标题">
                    </p>
                    <p>
                        <select name="type" class="form-control">
                            <option value="0">请选择文章分类</option>
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.type_name }}</option>
                            {% endfor %}

                        </select>
                    </p>
                    <p>
                        <textarea name="content" class="mytextarea">

                        </textarea>
                    </p>
                    <p></p>
                    <p style="text-align: right;">
                        <button type="submit" class="btn btn-primary">发表文章</button>
                    </p>

                </form>
            </div>
            <div class="right1" style="background-color: #00ff80"></div>
            <div class="right1" style="background-color: darkgreen"></div>
            <div class="right1" style="padding-top: 30px">
                <form action="{{ url_for('user.user_change') }}" method="post" enctype="multipart/form-data">
                    <p>
                        <textarea name="content" class="mytextarea">

                        </textarea>
                    </p>
                    <p></p>
                    <p style="text-align: right;">
                        <button type="submit" class="btn btn-primary">更改我的</button>
                    </p>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static',filename='tinymce/tinymce.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/center.js') }}"></script>
{% endblock %}

flaskblog/templates/user/index.html
{% extends 'base.html' %}
{% block title %}
    博客首页
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1200px;
            margin: 0 auto;
        }

        .article {
            width: 90%;
            margin: 20px auto;
            padding: 5px 10px;
            background-color: rgba(131, 202, 227, 0.7);
            border-bottom: 1px solid gray;
        }

        .article p {
            font-size: 14px;
        rgba(75, 75, 74, 1.00);
        }

        .article h4 a {
            color: rgba(80, 80, 79, 1.00);
        }

        .article h4 a:hover {
            color: black;
        }

        .article div span {
            margin-left: 20px;
        }

        .article div {
            margin-bottom: 18px;
        }

    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        {% for article in articles %}
            <div class="article">
                <h4><a href="">{{ article.title }}</a></h4>
                <p>
                    <span>作者：{{ article.user.username }}</span>
                    <br>
                    <br>
                <div>{{ article.content | cdecode | safe }}</div>
                </p>
                <div>
                    <span style="margin-left: 0">发布时间：{{ article.pdatetime }}</span>
                    <span>收藏:{{ article.save_num }}</span><span>点击量:{{ article.click_num }}</span><span>点赞量:{{ article.love_num }}</span>
                </div>
            </div>
        {% endfor %}

        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                <li class="active"><a href="#">2 <span class="sr-only">(current)</span></a></li>
                <li class="active"><a href="#">3 <span class="sr-only">(current)</span></a></li>
                <li class="active"><a href="#">4 <span class="sr-only">(current)</span></a></li>
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

flaskblog/templates/user/login.html
{% extends 'base.html' %}
{% block title %}
    用户注册
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
            height: 600px;
            margin: 0 auto;
        }

        #container h1 {
            text-align: center;
            margin-bottom: 50px;
        }

        #container form {

            margin: 0 auto;
        }

        #tab {
            font-size: 20px;
            text-align: left;
            padding-left: 250px;
            margin-bottom: 20px;
        }

        #tab span {
            display: inline-block;
            padding: 10px;
            text-align: center;
            cursor: default;
            color: #f3f3f3;
        }

        .tips {
            color: red;
            font-size: 14px;
        }

        #btnCheck {
            width: 140px;
        }
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        <h1>用户登录</h1>
        <div id="tab">
            <span>用户名 / 密码</span> | <span>手机验证码</span>
        </div>
        <div class="logintab">
            <p class="tips">{{ msg }}</p>
            <form class="form-horizontal" method="post" action="{{ url_for('user.login') }}?f=1">
                <div class="form-group">

                    <div class="col-md-6 col-md-offset-3">
                        <input type="text" class="form-control" id="inputUsername" placeholder="username"
                               name="username">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-3">
                        <input type="password" class="form-control" id="inputPassword" placeholder="password"
                               name="password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-10">
                        <button type="submit" class="btn btn-primary col-md-3">登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录
                        </button>
                        <button type="reset" class="btn btn-primary col-md-3 col-md-offset-1">重&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;置</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="logintab">
            <p class="tips">{{ msg }}</p>
            <form class="form-horizontal" method="post" action="{{ url_for('user.login') }}?f=2">
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-3">
                        <input type="text" class="form-control" id="inputPhone" placeholder="输入手机号码"
                               name="phone"><span></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 col-md-offset-3">
                        <input type="text" class="form-control" id="inputCode" placeholder="输入验证码"
                               name="code">
                    </div>
                    <div class="col-md-2">
                        <input type="button" id="btnCheck" class="btn btn-info" value="发送验证码"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-10">
                        <button type="submit" class="btn btn-primary col-md-3">登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录
                        </button>
                        <button type="reset" class="btn btn-primary col-md-3 col-md-offset-1">重&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;置</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
                // 显示|隐藏 登录方式
                $(".logintab").hide();
                $(".logintab").first().show();
                $("#tab span").each(function (i) {
                    $(this).click(function () {
                        $(".logintab").hide();
                        $(".logintab").eq(i).show();
                    })
                });

                // 发送验证码
                $('#btnCheck').click(function () {
                    let phone = $('#inputPhone').val();
                    let span_obj = $('#inputPhone').next('span');
                    span_obj.css({'color': 'red', 'font-size': '12px'});
                    if (phone.length == 11) {
                        //发送ajax
                        $.get('{{ url_for('user.send_message') }}', {phone: phone}, function (data) {
                            if (data.code == 200) {
                                alert('短信发送成功请查收！');
                            } else {
                                alert(data.msg);
                            }
                        });
                    } else {
                        span_obj.text('必须输入11位手机号码')
                    }
                });
            }
        )

    </script>
{% endblock %}

flaskblog/templates/user/register.html
{% extends 'base.html' %}
{% block title %}
    用户注册
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
            height: 600px;
            margin: 0 auto;
        }

        #container h1 {
            text-align: center;
            margin-bottom: 50px;
        }

        #container form {

            margin: 0 auto;
        }
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        <h1>用户注册</h1>
        <form class="form-horizontal" method="post" action="{{ url_for('user.register') }}">
            <div class="form-group">
                <label for="inputUsername" class="col-md-2 control-label col-md-offset-1">用户名</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" id="inputUsername" placeholder="username" name="username">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword" class="col-md-2 control-label col-md-offset-1">密码</label>
                <div class="col-md-6">
                    <input type="password" class="form-control" id="inputPassword" placeholder="password"
                           name="password">
                </div>
            </div>
            <div class="form-group">
                <label for="inputConfirm" class="col-md-2 control-label col-md-offset-1 ">确认密码</label>
                <div class="col-md-6">
                    <input type="password" class="form-control" id="inputConfirm" placeholder="confirm password"
                           name="repassword">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPhone" class="col-md-2 control-label col-md-offset-1">手机号码</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" id="inputPhone" placeholder="phone number" name="phone">
                    <span> </span>
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail" class="col-md-2 control-label col-md-offset-1">邮箱</label>
                <div class="col-md-6">
                    <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-10">
                    <button type="submit" class="btn btn-primary col-md-3">注&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;册
                    </button>
                    <button type="reset" class="btn btn-primary col-md-3 col-md-offset-1">重&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;置</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{# 添加js脚本 #}
{% block scripts %}
    {{ super() }}
    <script>
        $('#inputPhone').blur(function () {
            let phone = $(this).val();
            let span_ele = $(this).next('span');
            if (phone.length == 11) {
                span_ele.text('');
                $.get('{{ url_for('user.check_phone') }}', {phone: phone}, function (data) {
                    // {#console.log(data);#}
                    if (data.code != 200) {
                        span_ele.css({"color": "#ff0011", "font-size": "12px"});
                        span_ele.text(data.msg);
                    }
                })
            } else {
                span_ele.css({"color": "#ff0011", "font-size": "12px"});
                span_ele.text('手机格式错误');
            }

        })
    </script>
{% endblock %}